name: Python application CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Build and deploy
      run: |
        python main.py &
        sleep 3  # Wait for the Flask app to start

    - name: Perform post-deployment tests
      run: |
        curl -X GET http://localhost:5000/  # Sending a GET request to the running Flask app

    - name: Stop the Flask app
      run: |
        kill $(lsof -t -i:5000)  # Stop the Flask app after tests
